org: alexvirdee08
app: portfolio-contact
service: contact-mailer

functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
    events:
      - http:
          method: post
          path: contact-mailer
          cors: true

provider:
  name: aws
  runtime: nodejs12.0
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]